class Movie:
    def __init__(self, name: str, description: str, sub_genre: str, release_year: int, cast: str, director: str, rating: float, featured: bool, poster_url: str) -> None:
        self.name = name
        self.slug = name.lower().replace(' ', '-')
        self.description = description
        self.sub_genre = sub_genre
        self.release_year = release_year
        self.cast = cast
        self.director = director
        self.rating = rating
        self.featured = featured
        self.poster_url = poster_url


movies = [
    Movie("The Shining", "A family's winter retreat turns into a nightmare", "Classic/Horror", 1980,
          "Jack Nicholson, Shelley Duvall", "Stanley Kubrick", 8.4, False, "http://image.tmdb.org/t/p/w500/nRj5511mZdTl4saWEPoj9QroTIu.jpg"),
    Movie("Psycho", "A secretary encounters a mysterious motel owner", "Classic/Horror", 1960,
          "Anthony Perkins, Janet Leigh", "Alfred Hitchcock", 8.5, False, "http://image.tmdb.org/t/p/w500//yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg"),
    Movie("Halloween", "A masked killer stalks teenagers on Halloween night", "Classic/Horror", 1978,
          "Donald Pleasence, Jamie Lee Curtis", "John Carpenter", 7.8, False, "http://image.tmdb.org/t/p/w500//wijlZ3HaYMvlDTPqJoTCWKFkCPU.jpg"),
    Movie("The Exorcist", "A young girl is possessed by a demonic entity", "Classic/Horror", 1973,
          "Ellen Burstyn, Linda Blair", "William Friedkin", 8.0, False, "http://image.tmdb.org/t/p/w500//4IjRR2OW2itjQWQnmlUzvwLz9DQ.jpg"),
    Movie("Alien", "A crew on a spaceship encounters a deadly extraterrestrial", "Classic/Horror", 1979,
          "Sigourney Weaver, Tom Skerritt", "Ridley Scott", 8.4, False, "http://image.tmdb.org/t/p/w500//vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg"),
    Movie("The Texas Chain Saw Massacre", "A group of friends faces a family of cannibals", "Classic/Horror", 1974,
          "Marilyn Burns, Gunnar Hansen", "Tobe Hooper", 7.5, False, "http://image.tmdb.org/t/p/w500//kvaLXaC4RX8KLYkJkWWJCyMsEw3.jpg"),
    Movie("Night of the Living Dead", "The dead come back to life and prey on the living", "Classic/Horror", 1968,
          "Duane Jones, Judith O'Dea", "George A. Romero", 7.9, False, "http://image.tmdb.org/t/p/w500//b6yJXwYAXgqJKNdOrEQxxbQ8oG4.jpg"),
    Movie("Rosemary's Baby", "A pregnant woman suspects her neighbors are part of a satanic cult", "Classic/Horror", 1968,
          "Mia Farrow, John Cassavetes", "Roman Polanski", 8.0, False, "http://image.tmdb.org/t/p/w500//s8pdaHjxNPLXIA1WjSTWm00RJTz.jpg"),
    Movie("Jaws", "A giant man-eating great white shark terrorizes a beach town", "Classic/Horror", 1975,
          "Roy Scheider, Robert Shaw", "Steven Spielberg", 8.0, False, "http://image.tmdb.org/t/p/w500//lxM6kqilAdpdhqUl2biYp5frUxE.jpg"),
    Movie("A Nightmare on Elm Street", "A disfigured killer hunts teenagers in their dreams", "Classic/Horror", 1984,
          "Heather Langenkamp, Johnny Depp", "Wes Craven", 7.5, False, "http://image.tmdb.org/t/p/w500//wGTpGGRMZmyFCcrY2YoxVTIBlli.jpg"),
    Movie("The Babadook", "A single mother and her son are tormented by a supernatural creature", "Classic/Horror", 2014,
          "Essie Davis, Noah Wiseman", "Jennifer Kent", 6.8, False, "http://image.tmdb.org/t/p/w500//lszpCmmPCKHvzn2OBx7bAgXlfhC.jpg"),
    Movie("The Witch", "A family in 1630s New England is plagued by dark forces", "Classic/Horror", 2015,
          "Anya Taylor-Joy, Ralph Ineson", "Robert Eggers", 6.9, False, "http://image.tmdb.org/t/p/w500//o384OC1tCV8nCnozkM6y4MiSqsw.jpg"),
    Movie("Get Out", "A young African-American man uncovers a disturbing secret", "Classic/Horror", 2017,
          "Daniel Kaluuya, Allison Williams", "Jordan Peele", 7.7, False, "http://image.tmdb.org/t/p/w500//mE24wUCfjK8AoBBjaMjho7Rczr7.jpg"),
    Movie("Hereditary", "A family's dark secrets are revealed after the death of their grandmother", "Classic/Horror", 2018,
          "Toni Collette, Alex Wolff", "Ari Aster", 7.3, False, "http://image.tmdb.org/t/p/w500//p9fmuz2Oj3HtEJEqbIwkFGUhVXD.jpg"),
    Movie("It Follows", "A teenage girl is pursued by a supernatural entity", "Classic/Horror", 2014,
          "Maika Monroe, Keir Gilchrist", "David Robert Mitchell", 6.8, False, "http://image.tmdb.org/t/p/w500//iwnQ1JH1wdWrGYkgWySptJ5284A.jpg"),
    Movie("The Silence of the Lambs", "An FBI trainee seeks help from a cannibalistic serial killer", "Classic/Horror", 1991,
          "Jodie Foster, Anthony Hopkins", "Jonathan Demme", 8.6, False, "http://image.tmdb.org/t/p/w500//uS9m8OBk1A8eM9I042bx8XXpqAq.jpg"),
    Movie("The Ring", "A cursed videotape brings death to anyone who watches it", "Classic/Horror", 2002,
          "Naomi Watts, Martin Henderson", "Gore Verbinski", 7.1, False, "http://image.tmdb.org/t/p/w500//e2t5CKMox7tjv3iD3Ko7NdFa5lJ.jpg"),
    Movie("The Blair Witch Project", "Three filmmakers disappear while investigating a local legend", "Classic/Horror", 1999,
          "Heather Donahue, Joshua Leonard", "Daniel Myrick, Eduardo Sánchez", 6.5, False, "http://image.tmdb.org/t/p/w500//9050VGrYjYrEjpOvDZVAngLbg1f.jpg"),
    Movie("Let the Right One In", "A bullied young boy befriends a mysterious young girl who is a vampire", "Classic/Horror", 2008,
          "Kåre Hedebrant, Lina Leandersson", "Tomas Alfredson", 7.9, False, "http://image.tmdb.org/t/p/w500//4hezTKTuZMp0l2ufihKwPgLmfLg.jpg"),
    Movie("The Conjuring", "Paranormal investigators help a family terrorized by a dark presence", "Classic/Horror", 2013,
          "Vera Farmiga, Patrick Wilson", "James Wan", 7.5, False, "http://image.tmdb.org/t/p/w500//wVYREutTvI2tmxr6ujrHT704wGF.jpg"),
    Movie("Ringu", "A cursed videotape brings deadly consequences", "Supernatural Horror", 1998,
          "Nanako Matsushima, Hiroyuki Sanada", "Hideo Nakata", 7.2, False, "http://image.tmdb.org/t/p/w500//x3PIk93PTbxT88ohfeb26L1VpZw.jpg"),
    Movie("Ju-on: The Grudge", "A vengeful spirit haunts a cursed house", "Supernatural Horror", 2002,
          "Megumi Okina, Misaki Ito", "Takashi Shimizu", 6.7, False, "http://image.tmdb.org/t/p/w500//oulszWeFpIBbbLZbkJNQiYRlcQs.jpg"),
    Movie("A Tale of Two Sisters", "Two sisters return home to face a troubled past", "Supernatural Horror", 2003,
          "Im Soo-jung, Moon Geun-young", "Kim Jee-woon", 7.2, False, "http://image.tmdb.org/t/p/w500//l3exwhwyGE0NnHJ3lFQ7eXoBSkH.jpg"),
    Movie("Shutter", "A photographer discovers mysterious shadows in his pictures", "Supernatural Horror", 2004,
          "Ananda Everingham, Natthaweeranuch Thongmee", "Banjong Pisanthanakun, Parkpoom Wongpoom", 7.1, False, "http://image.tmdb.org/t/p/w500//bft6OyITsxSZuTxu2oJipApLran.jpg"),
    Movie("Dark Water", "A mother and daughter move into a haunted apartment building", "Supernatural Horror", 2002,
          "Hitomi Kuroki, Rio Kanno", "Hideo Nakata", 6.7, False, "http://image.tmdb.org/t/p/w500//cm4M9xaBu78IjuAVNG4LCXdXsg.jpg"),
    Movie("Train to Busan", "Passengers on a train fight to survive a zombie outbreak", "Zombie Horror", 2016,
          "Gong Yoo, Ma Dong-seok", "Yeon Sang-ho", 7.5, True, "http://image.tmdb.org/t/p/w500//vNVFt6dtcqnI7hqa6LFBUibuFiw.jpg"),
    Movie("Us", "A family is terrorized by their doppelgängers", "Featured Movies", 2019,
          "Lupita Nyong'o, Winston Duke", "Jordan Peele", 6.8, True, "http://image.tmdb.org/t/p/w500//ux2dU1jQ2ACIMShzB3yP93Udpzc.jpg"),
    Movie("A Quiet Place", "A family must remain silent to avoid mysterious creatures", "Featured Movies", 2018,
          "Emily Blunt, John Krasinski", "John Krasinski", 7.5, True, "http://image.tmdb.org/t/p/w500//nAU74GmpUk7t5iklEp3bufwDq4n.jpg"),
    Movie("Midsommar", "A group of friends attends a sinister Swedish festival", "Featured Movies", 2019,
          "Florence Pugh, Jack Reynor", "Ari Aster", 7.1, True, "http://image.tmdb.org/t/p/w500//rnypzzV2WDbHQkteEnpF0SsLlbT.jpg"),
    Movie("The Lighthouse", "Two lighthouse keepers face madness and isolation", "Featured Movies", 2019,
          "Willem Dafoe, Robert Pattinson", "Robert Eggers", 7.5, True, "http://image.tmdb.org/t/p/w500//3nk9UoepYmv1G9oP18q6JJCeYwN.jpg"),
    Movie("Annihilation", "A group of scientists explores a mysterious and deadly phenomenon", "Featured Movies", 2018,
          "Natalie Portman, Jennifer Jason Leigh", "Alex Garland", 6.8, True, "http://image.tmdb.org/t/p/w500//4YRplSk6BhH6PRuE9gfyw9byUJ6.jpg"),
    Movie("The Invisible Man", "A woman believes she is being hunted by her abusive ex", "Featured Movies", 2020,
          "Elisabeth Moss, Aldis Hodge", "Leigh Whannell", 7.1, True, "http://image.tmdb.org/t/p/w500//5EufsDwXdY2CVttYOk2WtYhgKpa.jpg"),
    Movie("It", "A group of kids faces an evil clown in their small town", "Featured Movies", 2017,
          "Jaeden Martell, Bill Skarsgård", "Andy Muschietti", 7.3, True, "http://image.tmdb.org/t/p/w500//9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg"),
    Movie("Ready or Not", "A bride's wedding night turns into a deadly game", "Featured Movies", 2019,
          "Samara Weaving, Adam Brody", "Matt Bettinelli-Olpin, Tyler Gillett", 6.8, True, "http://image.tmdb.org/t/p/w500//vOl6shtL0wknjaIs6JdKCpcHvg8.jpg"),
    Movie("One Missed Call", "A series of mysterious phone calls predicts the recipient's death", "Featured Movies", 2003,
          "Kō Shibasaki, Shinichi Tsutsumi", "Takashi Miike", 6.2, True, "http://image.tmdb.org/t/p/w500//9pIvQaQV0sMHx7d3Ys9qTK9YqTZ.jpg"),
    Movie("Black Swan", "A ballet dancer descends into madness", "Psychological Horror", 2010,
          "Natalie Portman, Mila Kunis", "Darren Aronofsky", 8.0, False, "http://image.tmdb.org/t/p/w500//8XYghKF0xkxp5A7QtK2F5vffdpZ.jpg"),
    Movie("Shutter Island", "A U.S. Marshal investigates a hospital for the criminally insane", "Psychological Horror", 2010,
          "Leonardo DiCaprio, Mark Ruffalo", "Martin Scorsese", 8.2, False, "http://image.tmdb.org/t/p/w500//4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg"),
    Movie("The Others", "A mother and her children experience supernatural occurrences in their house", "Psychological Horror", 2001,
          "Nicole Kidman, Alakina Mann", "Alejandro Amenábar", 7.6, False, "http://image.tmdb.org/t/p/w500//p8g1vlTvpM6nr2hMMiZ1fUlKF0D.jpg"),
    Movie("Jacob's Ladder", "A Vietnam War veteran experiences strange visions and paranoia", "Psychological Horror", 1990,
          "Tim Robbins, Elizabeth Peña", "Adrian Lyne", 7.5, False, "http://image.tmdb.org/t/p/w500//4GY4FsM0ZOtbSTeMpY0g4WkEuBW.jpg"),
    Movie("Don't Breathe", "A group of thieves gets trapped in a blind man's house", "Home Invasion", 2016,
          "Jane Levy, Dylan Minnette", "Fede Álvarez", 7.1, False, "http://image.tmdb.org/t/p/w500//kkUMGON2uFRlxI3zIMFdjqARnbb.jpg"),
    Movie("The Strangers", "A couple is terrorized by masked strangers in their remote vacation home", "Home Invasion", 2008,
          "Liv Tyler, Scott Speedman", "Bryan Bertino", 6.2, False, "http://image.tmdb.org/t/p/w500//9zsA2xafNMA8BQmpQLdppLIGYAE.jpg"),
    Movie("Funny Games", "A wealthy family is subjected to sadistic games by two young men", "Home Invasion", 2007,
          "Naomi Watts, Tim Roth", "Michael Haneke", 6.5, False, "http://image.tmdb.org/t/p/w500//qzweZTBnVgEROyiSP4QPBoT7uBV.jpg"),
    Movie("Hush", "A deaf writer fights for her life against a masked killer", "Home Invasion", 2016,
          "Kate Siegel, John Gallagher Jr.", "Mike Flanagan", 6.6, False, "http://image.tmdb.org/t/p/w500//zHzBTd502IZf60x8n2g0TB01vPF.jpg"),
    Movie("The Purge", "In a dystopian future, all crime is legal for one night each year", "Home Invasion", 2013,
          "Ethan Hawke, Lena Headey", "James DeMonaco", 5.7, False, "http://image.tmdb.org/t/p/w500//x6hwbnR2nGacSzljqYaXY25w1Me.jpg"),
    Movie("Paranormal Activity", "A couple experiences supernatural occurrences in their new home", "Found Footage", 2007,
          "Katie Featherston, Micah Sloat", "Oren Peli", 6.3, False, "http://image.tmdb.org/t/p/w500//tmclkEpjeo4Zu564gf3KrwIOuKw.jpg"),
    Movie("Cloverfield", "A group of friends documents their experience during a monster attack", "Found Footage", 2008,
          "Michael Stahl-David, Jessica Lucas", "Matt Reeves", 7.0, False, "http://image.tmdb.org/t/p/w500//qIegUGJqyMMCRjkKV1s7A9MqdJ8.jpg"),
    Movie("REC", "A reporter and cameraman follow firefighters into a building infected by a deadly virus", "Found Footage", 2007,
          "Manuela Velasco, Ferran Terraza", "Jaume Balagueró, Paco Plaza", 7.4, False, "http://image.tmdb.org/t/p/w500//7pZDYaQSDA0S6RdDYYzhktxeiAa.jpg"),
    Movie("Blair Witch", "A group of students disappear while filming a documentary in the woods", "Found Footage", 2016,
          "James Allen McCune, Callie Hernandez", "Adam Wingard", 5.0, False, "http://image.tmdb.org/t/p/w500//chgLLNv3bMSOptaciOUPtDcAggq.jpg"),
    Movie("Grave Encounters", "A ghost-hunting reality show crew gets trapped in a haunted asylum", "Found Footage", 2011,
          "Sean Rogerson, Juan Riedinger", "The Vicious Brothers", 6.1, False, "http://image.tmdb.org/t/p/w500//8vnsB3Rg9Gb91UOaecXRb7dYB37.jpg"),
    Movie("28 Days Later", "A man wakes up from a coma to find a world overrun by zombies", "Zombie Horror", 2002,
          "Cillian Murphy, Naomie Harris", "Danny Boyle", 7.6, False, "http://image.tmdb.org/t/p/w500//sQckQRt17VaWbo39GIu0TMOiszq.jpg"),
    Movie("Dawn of the Dead", "Survivors take refuge from zombies in a shopping mall", "Zombie Horror", 2004,
          "Sarah Polley, Ving Rhames", "Zack Snyder", 7.3, False, "http://image.tmdb.org/t/p/w500//ttquyxStEEctzghtA2f4PUGprDr.jpg"),
    Movie("Zombieland", "A group of survivors navigates a zombie-infested America", "Zombie Horror", 2009,
          "Jesse Eisenberg, Woody Harrelson", "Ruben Fleischer", 7.6, False, "http://image.tmdb.org/t/p/w500//dUkAmAyPVqubSBNRjRqCgHggZcK.jpg"),
    Movie("Shaun of the Dead", "A man tries to save his friends and family during a zombie apocalypse", "Zombie Horror", 2004,
          "Simon Pegg, Nick Frost", "Edgar Wright", 7.9, False, "http://image.tmdb.org/t/p/w500//dgXPhzNJH8HFTBjXPB177yNx6RI.jpg"),
    Movie("I Am Legend", "The last man on Earth battles infected mutants", "Post-Apocalyptic", 2007,
          "Will Smith, Alice Braga", "Francis Lawrence", 7.2, False, "http://image.tmdb.org/t/p/w500//iPDkaSdKk2jRLTM65UOEoKtsIZ8.jpg"),
    Movie("The Road", "A father and son journey through a post-apocalyptic wasteland", "Post-Apocalyptic", 2009,
          "Viggo Mortensen, Kodi Smit-McPhee", "John Hillcoat", 7.2, False, "http://image.tmdb.org/t/p/w500//qLaXnLzqleBWQtjvZ6JGVSaKoC3.jpg"),
    Movie("Mad Max: Fury Road", "A woman rebels against a tyrannical ruler in a desert wasteland", "Post-Apocalyptic", 2015,
          "Tom Hardy, Charlize Theron", "George Miller", 8.1, False, "http://image.tmdb.org/t/p/w500//hA2ple9q4qnwxp3hKVNhroipsir.jpg"),
    Movie("Snowpiercer", "Survivors on a perpetually-moving train face class warfare", "Post-Apocalyptic", 2013,
          "Chris Evans, Song Kang-ho", "Bong Joon-ho", 7.1, False, "http://image.tmdb.org/t/p/w500//nzccOvhrLGI0nvAknCEAk8bchD9.jpg"),
    Movie("The Book of Eli", "A man protects a sacred book in a post-apocalyptic world", "Post-Apocalyptic", 2010,
          "Denzel Washington, Gary Oldman", "Albert Hughes, Allen Hughes", 6.9, False, "http://image.tmdb.org/t/p/w500//1H1y9ZiqNFaLgQiRDDZLA55PviW.jpg"),
    Movie("The Conjuring", "Paranormal investigators help a family terrorized by a dark presence", "Supernatural Horror", 2013,
          "Vera Farmiga, Patrick Wilson", "James Wan", 7.5, False, "http://image.tmdb.org/t/p/w500//wVYREutTvI2tmxr6ujrHT704wGF.jpg"),
]

def get_rating(movie: Movie):
    return movie.rating